spring:
  application:
    name: "warehouse-software"
  devtools:
    add-properties: false
  datasource:
    url: jdbc:h2:file:./warehousedb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    #defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false

server:
  port: 8095
  ssl:
    enabled: false
  servlet:
    context-path: /${spring.application.name}
